---
# tasks file for apigee-opdk-setup-silent-file
- name: Update cache with manual_response_file if provided
  cache:
    key: 'manual_response_file'
    value: '{{ manual_response_file }}'
  when: manual_response_file is defined

- name: Construct the Edge response file
  cache:
    key: opdk_installation_config_file
    value: "{{ opdk_installer_path }}/edge-response-{{ opdk_version }}-{{ region }}.conf"

- name: Remove the old response file
  become: yes
  file:
    path: "{{ opdk_installation_config_file }}"
    state: absent
  when: manual_response_file is not defined or not manual_response_file

- name: Fail if ldap password is not provided
  fail:
    msg: "Ldap password is required, please provide ldap password"
  when: opdk_ldap_pass is not defined or opdk_ldap_pass == ""

- name: Generate Cassandra IP and Rack configuration
  include_tasks: cassandra.yml

- name: Set attributes for Postgres Master & Standby replication if available
  include_tasks: postgres.yml

- name: Regional LDAP IP for dc-1 if replicating LDAP
  set_fact:
    opdk_ldap_sid: '1'
    opdk_ldap_peer: "{{ hostvars[groups['dc-2-ldap'][0]]['private_address'] }}"
  when: region == 'dc-1' and opdk_ldap_type == '2' and groups['dc-2-ldap'] is defined

- name: Regional LDAP IP for dc-2 if replicating LDAP
  set_fact:
    opdk_ldap_sid: '2'
    opdk_ldap_peer: "{{ hostvars[groups['dc-1-ldap'][0]]['private_address'] }}"
  when: region == 'dc-2' and opdk_ldap_type == '2' and groups['dc-1-ldap'] is defined

- name: Ensure that a folder exists for the file to be generated
  become: yes
  file:
    path: "{{ opdk_installation_config_file | dirname }}"
    state: directory

- name: Construct name of the response file
  cache:
    key: 'opdk_installation_config_file'
    value: '{{ opdk_installer_path }}/edge-response-{{ opdk_version }}-{{ region }}.conf'

- name: Touch file
  become: yes
  file:
    state: touch
    path: "{{ opdk_installation_config_file }}"

- name: Assert that all necessary attributes have been provided
  assert:
    that:
      - enable_system_check is defined
      - local_mgmt_ip is defined
      - opdk_user_email is defined
      - opdk_user_pass is defined
      - opdk_license_target_file_path is defined
      - use_opdk_ldap_remote_host is defined
      - opdk_ldap_pass is defined
      - opdk_ldap_sid is defined
      - opdk_ldap_type is defined
      - opdk_ldap_port is defined
      - opdk_enable_ax is defined
      - opdk_mp_pod is defined
      - region is defined
      - opdk_use_zk_cluster is defined
      - groups['ds'] is defined
      - groups['dc-1-ds'] is defined
      - opdk_use_cass_cluster is defined
      - opdk_cass_username is defined
      - opdk_cass_password is defined
      - opdk_cass_auth is defined
      - opdk_smtp_skip is defined
      - opdk_smtp_mail_from is defined
      - opdk_user_name is defined
      - pg_pass is defined
      - opdk_monetization is defined
    msg: "Please provide the missing attributes, it can be either added to either custom-properties.yml or credentials.yml or passed as -e key=value"

- name: Assert that LDAP replication attributes are available
  assert:
    that:
      - opdk_ldap_ip is defined
      - opdk_ldap_peer is defined
    msg: "Please provide the missing attributes, it can be either added to either custom-properties.yml or credentials.yml or passed as -e key=value"
  when: opdk_ldap_type == '2'

- name: Construct the silent-install file
  become: yes
  template:
    src: 'silent-install.conf.j2'
    dest: "{{ opdk_installation_config_file }}"
    force: yes
    owner: '{{ opdk_user_name }}'
    group: '{{ opdk_group_name }}'
    mode: 0655
  when: manual_response_file is not defined or not manual_response_file
  tags: ['no-silent-install']

- name: Copy provided silent-install file
  become: yes
  copy:
    src: "{{ manual_response_file }}"
    dest: "{{ opdk_installation_config_file }}"
    owner: '{{ opdk_user_name }}'
    group: '{{ opdk_group_name }}'
    mode: 0655
  when: manual_response_file is defined and manual_response_file
  tags: ['no-silent-install']
