---
# tasks file for opdk-setup-silent-file
- name: Remove the old response file
  file:
    path: "{{ opdk_installation_config_file }}"
    state: absent

- name: Fail if ldap password is not provided
  fail:
    msg: "Ldap password is required, please provide ldap password"
  when: opdk_ldap_pass is not defined or opdk_ldap_pass == ""

- name: Fail if cassandra user name is not provided
  fail:
    msg: 'cassandra user name is required, please provide cassandra user name'
  when: opdk_cass_username is not defined or opdk_cass_username == ""

- name: Fail if cassandra user password is not provided
  fail:
    msg: 'cassandra user password is required, please provide cassandra user password'
  when: opdk_cass_password is not defined or opdk_cass_password == ""

- name: Fail if ds group is not provided
  fail:
    msg: 'ds group is not defined in the inventory file, please define the ds group in the inventory file'
  when: groups['ds'] is not defined

- name: Construct cassandra hosts configuration
  cassandra_hosts:
    inventory_hostname: '{{ inventory_hostname }}'
    hostvars: '{{ hostvars }}'

- name: Construct cassandra hosts configuration
  cassandra_hosts:
    inventory_hostname: '{{ apigee_topology.__repr__().encode('base64') }}'
    hostvars: '{{ hostvars }}'

- name: Construct the silent-install file
  template:
    src: 'silent-install.conf.j2'
    dest: "{{ opdk_installation_config_file }}"
    force: yes
    owner: '{{ opdk_user_name }}'
    group: '{{ opdk_group_name }}'
    mode: 0644
  when: provided_response_file is not defined or not provided_response_file

- name: Copy provided silent-install file
  copy:
    src: "{{ provided_response_file }}"
    dest: "{{ opdk_installation_config_file }}"
    owner: '{{ opdk_user_name }}'
    group: '{{ opdk_group_name }}'
    mode: 0644
  when: provided_response_file is defined and provided_response_file
