---
# tasks file for apigee-opdk-setup-silent-file
- name: Remove the old response file
  file:
    path: "{{ opdk_installation_config_file }}"
    state: absent
  when: provided_response_file is not defined or not provided_response_file

- name: Fail if ldap password is not provided
  fail:
    msg: "Ldap password is required, please provide ldap password"
  when: opdk_ldap_pass is not defined or opdk_ldap_pass == ""

- include: cassandra.yml

- name: Ensure that a folder exists for the file to be generated
  file:
    path: "{{ opdk_installation_config_file | dir }}"
    state: directory

- name: Construct the silent-install file
  template:
    src: 'silent-install.conf.j2'
    dest: "{{ opdk_installation_config_file }}"
    force: yes
    owner: '{{ opdk_user_name }}'
    group: '{{ opdk_group_name }}'
    mode: 0655
  when: provided_response_file is not defined or not provided_response_file
  tags:
  - no-silent-install

- name: Copy provided silent-install file
  copy:
    src: "{{ provided_response_file }}"
    dest: "{{ opdk_installation_config_file }}"
    owner: '{{ opdk_user_name }}'
    group: '{{ opdk_group_name }}'
    mode: 0655
  when: provided_response_file is defined and provided_response_file
  tags:
  - no-silent-install
